// templates/react/js/scss/src/App.jsx
import React, { useState } from "react";

const App = () => {
  const [count, setCount] = useState(0);

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gray-900 text-white">
      <header className="flex items-center space-x-4 p-8">
        <h1 className="text-4xl font-bold">
          Vite + React + Tailwind CSS + SASS
        </h1>
      </header>

      <main className="flex flex-col items-center">
        <div className="flex flex-col items-center">
          <button
            onClick={() => setCount((count) => count + 1)}
            className="px-6 py-2 bg-blue-500 text-white font-semibold rounded-lg shadow hover:bg-blue-600 transition-all duration-200"
          >
            Count is: {count}
          </button>
          <p className="mt-4 text-gray-400">
            Edit{" "}
            <code className="bg-gray-800 px-1 py-0.5 rounded">src/App.jsx</code>{" "}
            and save to test HMR
          </p>
        </div>
      </main>

      <footer className="mt-12 p-4 text-center text-gray-500 text-xs">
        <p>Click on the Vite, React or Sass logos to learn more</p>
        <div className="flex justify-center space-x-6 mt-2">
          <a
            href="https://vitejs.dev"
            target="_blank"
            rel="noopener noreferrer"
          >
            <img src="/assets/vite.svg" alt="Vite logo" className="w-10 h-10" />
          </a>
          <a
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            <img
              src="/assets/react.svg"
              alt="React logo"
              className="w-10 h-10"
            />
          </a>
          <a
            href="https://sass-lang.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <img
              src="/assets/sass.svg"
              alt="Sass logo"
              className="w-10 h-10"
            />
          </a>
        </div>
      </footer>
    </div>
  );
};

export default App;

// src/templates/vue/js/scss/src/App.vue
<script setup>
import HelloWorld from './components/HelloWorld.vue'
</script>

<template>
  <div class="flex items-center justify-center p-0">
    <a href="https://vite.dev" target="_blank">
      <img src="./assets/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
    <a href="https://tailwindcss.com/" target="_blank">
      <img src="./assets/tailwindcss.svg" class="logo tailwind" alt="Tailwind logo" />
    </a>
    <a href="https://sass-lang.com/" target="_blank">
      <img src="./assets/sass.svg" class="logo sass" alt="Sass logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue + Tailwind + Sass" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
.logo.tailwind:hover {
  filter: drop-shadow(0 0 2em #06b6d4);
}
.logo.sass:hover {
  filter: drop-shadow(0 0 2em #CD6799);
}
</style>
